// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSFN-3XcJrye_dRJcsfFErCnJUMRxYx10',
    appId: '1:954510833269:web:86cf0e4fbac4ddc17f2a3c',
    messagingSenderId: '954510833269',
    projectId: 'awesometicks-e98c9',
    authDomain: 'awesometicks-e98c9.firebaseapp.com',
    storageBucket: 'awesometicks-e98c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjLVAVX-BsBdDL_OCnHmCuMGydV49U7O8',
    appId: '1:954510833269:android:b77364265b4b4b857f2a3c',
    messagingSenderId: '954510833269',
    projectId: 'awesometicks-e98c9',
    storageBucket: 'awesometicks-e98c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHIZTYaImARtmPCgGInVQYLA5iNAfa0_g',
    appId: '1:954510833269:ios:6c7fa8820973a3627f2a3c',
    messagingSenderId: '954510833269',
    projectId: 'awesometicks-e98c9',
    storageBucket: 'awesometicks-e98c9.firebasestorage.app',
    iosBundleId: 'com.nectar.awesometicksnew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHIZTYaImARtmPCgGInVQYLA5iNAfa0_g',
    appId: '1:954510833269:ios:542a581f298e04d47f2a3c',
    messagingSenderId: '954510833269',
    projectId: 'awesometicks-e98c9',
    storageBucket: 'awesometicks-e98c9.firebasestorage.app',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSFN-3XcJrye_dRJcsfFErCnJUMRxYx10',
    appId: '1:954510833269:web:9fae15cb72bc004a7f2a3c',
    messagingSenderId: '954510833269',
    projectId: 'awesometicks-e98c9',
    authDomain: 'awesometicks-e98c9.firebaseapp.com',
    storageBucket: 'awesometicks-e98c9.firebasestorage.app',
  );
}
